name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: health check
        uses: jtalk/url-health-check-action@v5
        with:
          url: https://fullstackopen-hhdt.onrender.com/
