name: Deployment pipeline

on:
  push:
    branches: [main]
    paths:
      - "part11/pokedex/**"
      - ".github/workflows/part11-pipeline.yaml"
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: part11/pokedex
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
      - name: Install Playwright browser
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npm run test:e2e -- --project=chromium

  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' &&  !contains(join(github.event.head_commit.message, ' '), '#skip')}}
        run: curl ${{ secrets.POKEDEX_RENDER_DEPLOY_HOOK }}
      - name: Trigger Deploy Success
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() && github.event_name == 'push' &&  !contains(join(github.event.head_commit.message, ' '), '#skip')}}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: success
          title: "New version of Pokedex deployed"

  notify_failure:
    needs: [build_and_test, deploy]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          title: "Build failed"
          description: "Commit ${{ github.event.head_commit.url }} by ${{ github.actor }} broke the build"

  notify_success:
    needs: [deploy]
    if: ${{ success() && github.event_name == 'push' &&  !contains(join(github.event.head_commit.message, ' '), '#skip')}}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Success
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: success
          title: "New version of Pokedex deployed"

  tag_release:
    needs: [deploy]
    if: github.event_name == 'push' &&  !contains(join(github.event.head_commit.message, ' '), '#skip')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch
